postgres:
  host: "teslatrack-stage-do-user-2432224-0.db.ondigitalocean.com"
  port: 25060
  user: "doadmin"
  password: "a3uot0pp9bxzcxoa"
  dbname: "defaultdb"
  sslmode: "require"

redis:
  host: "157.230.142.205:6379"
  password: "FkNU6btkbjp+RwIG9529yJZG+EfNboVHEC6FzhpifbNMC0fIPC/MJP0/kvo3GYuT7LgkhGDVfE1gEDch"