teslatrack:
  fetch: true

postgres:
  host: "teslatrack-stage-do-user-2432224-0.db.ondigitalocean.com"
  port: 25060
  user: "doadmin"
  password: "a3uot0pp9bxzcxoa"
  dbname: "defaultdb"
  sslmode: "require"

redis:
  host: "teslatrack-redis-stage-do-user-2432224-0.db.ondigitalocean.com:25061"
  password: "qdl9g23jherwdh7f"