apiVersion: apps/v1
kind: Deployment
metadata:
  name: teslatrack-api
  labels:
    app: teslatrack-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teslatrack-api
  template:
    metadata:
      labels:
        app: teslatrack-api
    spec:
      imagePullSecrets:
      - name: do-registry
      containers:
      - name: teslatrack-api
        image: registry.digitalocean.com/teslatrack/teslatrack_api:0.0.12
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

