apiVersion: apps/v1
kind: Deployment
metadata:
  name: teslatrack-api
  labels:
    app: teslatrack-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teslatrack-api
  template:
    metadata:
      labels:
        app: teslatrack-api
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: teslatrack-api
        image: christopherwong/teslatrack:0.0.8
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

